version: "3.8"

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9003:9001" #използвам 9001, за това 9003
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address :9001
    networks:
      - service_network
    volumes:
      - minio_data:/data

  app:
    build: ./src
    container_name: fms
    ports:
      - "5000:5000"
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    depends_on:
      - minio
      - keycloak
    networks:
      - service_network
    volumes:
      - ./src:/app

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_HOSTNAME=localhost
      - KC_HOSTNAME=localhost
    ports:
      - "8080:8080"
    command:
      - start-dev
    restart: unless-stopped
    volumes:
      - ./keycloak:/opt/keycloak/data

networks:
  service_network:
    driver: bridge

volumes:
  minio_data:
    driver: local